parameters:
    pim_custom_entity.datasource.custom_entity: Pim\Bundle\CustomEntityBundle\Datasource\CustomEntityDatasource

services:
    pim_custom_entity.datasource.custom_entity:
        class: %pim_custom_entity.datasource.custom_entity%
        parent: pim_datagrid.datasource.default
        arguments:
            - '@pim_catalog.helper.locale'
        tags:
            - { name: oro_datagrid.datasource, type: pim_custom_entity }
